services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: columb-shop-app
    restart: unless-stopped
    ports:
      - "${APP_PORT_HOST:-3001}:3000"
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: "file:/usr/src/app/prisma/db/prod.db"
    volumes:
      - sqlite_data:/usr/src/app/prisma/db

volumes:
  sqlite_data:
